### ISSUE TITLE
Désactiver l'emoji picker dans GitHub, GitLab, Discourse…

### ISSUE THREAD

**Issue by stephane-klein** [stephane-klein/personnal-notebook#22]
Chercher une solution (extension Firefox/Chrome) pour désactiver dans GitHub, GitLab, [Discourse](https://github.com/discourse/discourse) le picker qui s'affiche automatiquement après la saisie de ` : `, exemple :

<img src='https://user-images.githubusercontent.com/54498080/178115167-55aa19d4-9a5a-4cb5-84fd-dd68b6e108ff.png' width='300' />

[En typographie Française](https://fr.wikipedia.org/wiki/Deux-points#Typographie), « le deux-points habituel est séparé du caractère qui le précède par une espace insécable », ce qui n'est pas le cas en anglais.  
Conséquence : ce fonctionnement est pénible lors de la rédaction en français, parce que l'insertion d'emoji est généralement pas souhaité et la fermeture du picker est une action pénible.

## Todo

- [x] Chercher sur GitHub si je trouve une extension Firefox/Chrome
- [ ] ~~Chercher dans le Firefox extension store si je trouve quelque chose~~
- [ ] ~~Chercher sur Reddit~~
- [ ] ~~Si aucune solution trouvée, poser la question dans un subreditt~~
- [x] Créer et publier un userstyle
- [ ] Tester le userstyle sous Chrome
- [ ] ...

**Comment by stephane-klein** [comment]
https://gitlab.com/gitlab-org/gitlab/-/issues/20231

**Comment by stephane-klein** [comment]
https://gitlab.com/gitlab-org/gitlab/-/issues/20231#note_981221945

**Comment by stephane-klein** [comment]
J'ai créé ce "styles" Userstyles qui permet de désactiver le emoji Picker sous GitHub et GitLab (sur les domaines qui contiennent `gitlab` dans le nom de domaine) : https://userstyles.org/styles/244590/disable-gitlab-github-emoji-picker

**Comment by stephane-klein** [comment]
J'ai tweeter https://twitter.com/klein_stephane/status/1545875737428869121
